FROM registry.ci.openshift.org/ocp/4.10:base
COPY machine-config-daemon /usr/bin/machine-config-daemon
COPY exampleCurrentConfig.json /etc/machine-config-daemon/currentConfig.json
COPY exampleDesiredConfig.json /etc/machine-config-daemon/desiredConfig.json
