apiVersion: v1
kind: ConfigMap
metadata:
  name: test-machineconfig-gpg
  namespace: clusters
data:
  config: |
    apiVersion: machineconfiguration.openshift.io/v1
    kind: MachineConfig
    metadata:
      labels:
        machineconfiguration.openshift.io/role: worker
      name: 99-test
    spec:
      config:
        ignition:
          version: 3.2.0
        storage:
          files:
          - contents:
              source: data:,hello%20world%0A
            mode: 420
            overwrite: true
            path: /etc/machine-config-daemon/no-reboot/containers-gpg.pub
