apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: machine-config-daemon-hypershift
  namespace: hypershift-mco
roleRef:
  kind: ClusterRole
  name: machine-config-daemon-hypershift
subjects:
- kind: ServiceAccount
  namespace: hypershift-mco
  name: machine-config-daemon-hypershift
