apiVersion: v1
kind: ConfigMap
metadata:
  name: desired-config
  namespace: hypershift-mco
data:
  config: |
    {"kind":"MachineConfig","apiVersion":"machineconfiguration.openshift.io/v1","metadata":...}
