apiVersion: hypershift.openshift.io/v1alpha1
kind: NodePool
metadata:
  name: inplace-demo
  namespace: clusters
spec:
  clusterName: example
  management:
    autoRepair: false
    upgradeType: InPlace
  nodeCount: 2
  platform:
    aws:
      instanceProfile: example-d4jhf-worker
      instanceType: m5.large
      rootVolume:
        size: 120
        type: gp3
      securityGroups:
        - id: sg-0e72abb1084c06be9
      subnet:
        id: subnet-0cfaadbcce790d335
    type: AWS
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.10.6-x86_64
